import type { SnapshotInput } from "./intelligenceEngine";
import type { DomainEvent } from "./domainEvents";

export type GraphNodeKind = "asset" | "defect" | "evidence" | "mission" | "telemetry" | "event" | "risk" | "information_gap";
export type GraphEdge = { id: string; source: string; target: string; relationship: "affects" | "observed_by" | "supports" | "targets" | "captured_by" | "propagates_to" | "precedes" | "contradicts"; confidence: number; timestamp?: string; provenance: string };
export type GraphNode = { id: string; kind: GraphNodeKind; label: string; confidence: number; observedAt?: string; state: "OBSERVED" | "CALCULATED" | "INFERRED" | "SIMULATED" | "UNKNOWN"; attributes: Record<string, unknown> };
export type WorldGraph = { algorithm: "drift-world-graph-v1"; nodes: GraphNode[]; edges: GraphEdge[]; generatedAt: string };

function node(id: string, kind: GraphNodeKind, label: string, confidence: number, state: GraphNode["state"], attributes: Record<string, unknown>, observedAt?: Date | string): GraphNode { return { id, kind, label, confidence, state, attributes, observedAt: observedAt ? new Date(observedAt).toISOString() : undefined }; }
export function buildWorldGraph(input: SnapshotInput, events: DomainEvent[] = []): WorldGraph {
  const nodes: GraphNode[] = []; const edges: GraphEdge[] = [];
  for (const asset of input.assets) nodes.push(node(`asset:${asset.id}`, "asset", asset.name, Math.min(1, (asset.criticality ?? 1) / 5), "OBSERVED", { assetType: asset.assetType, latitude: asset.latitude, longitude: asset.longitude, status: asset.status }, asset.updatedAt));
  for (const mission of input.missions) { nodes.push(node(`mission:${mission.id}`, "mission", mission.name, .95, "OBSERVED", { status: mission.status, assetId: mission.assetId }, mission.createdAt)); edges.push({ id: `mission:${mission.id}->asset:${mission.assetId}`, source: `mission:${mission.id}`, target: `asset:${mission.assetId}`, relationship: "targets", confidence: .95, timestamp: new Date(mission.createdAt).toISOString(), provenance: "missions.assetId" }); }
  for (const evidence of input.evidence) nodes.push(node(`evidence:${evidence.id}`, "evidence", evidence.fileName, evidence.qualityStatus === "pass" ? .9 : evidence.qualityStatus === "fail" ? .2 : .55, "OBSERVED", { source: evidence.source, qualityStatus: evidence.qualityStatus, latitude: evidence.latitude, longitude: evidence.longitude }, evidence.createdAt));
  for (const defect of input.defects) { const confidence = Math.max(0, Math.min(1, (defect.confidencePercent ?? 0) / 100)); nodes.push(node(`defect:${defect.id}`, "defect", defect.label, confidence, defect.reviewState === "approved" ? "OBSERVED" : "INFERRED", { severity: defect.severity, assetId: defect.assetId, missionId: defect.missionId, status: defect.status }, defect.createdAt)); edges.push({ id: `asset:${defect.assetId}->defect:${defect.id}`, source: `asset:${defect.assetId}`, target: `defect:${defect.id}`, relationship: "affects", confidence, timestamp: new Date(defect.createdAt).toISOString(), provenance: "defects.assetId" }); if (defect.evidenceId) edges.push({ id: `evidence:${defect.evidenceId}->defect:${defect.id}`, source: `evidence:${defect.evidenceId}`, target: `defect:${defect.id}`, relationship: "supports", confidence, timestamp: new Date(defect.createdAt).toISOString(), provenance: "defects.evidenceId" }); edges.push({ id: `mission:${defect.missionId}->defect:${defect.id}`, source: `mission:${defect.missionId}`, target: `defect:${defect.id}`, relationship: "observed_by", confidence: .85, timestamp: new Date(defect.createdAt).toISOString(), provenance: "defects.missionId" }); }
  for (const point of input.telemetry) { const id = `telemetry:${point.id}`; nodes.push(node(id, "telemetry", "Telemetry sample", .8, "OBSERVED", { latitude: point.latitude, longitude: point.longitude, batteryPercent: point.batteryPercent }, point.capturedAt)); edges.push({ id: `${id}->mission:${point.missionId}`, source: id, target: `mission:${point.missionId}`, relationship: "captured_by", confidence: .8, timestamp: new Date(point.capturedAt).toISOString(), provenance: "telemetry.missionId" }); }
  for (const event of events) { const id = `event:${event.eventId}`; nodes.push(node(id, "event", event.type, .8, "OBSERVED", event.payload, event.occurredAt)); const target = event.defectId ? `defect:${event.defectId}` : event.evidenceId ? `evidence:${event.evidenceId}` : event.assetId ? `asset:${event.assetId}` : event.missionId ? `mission:${event.missionId}` : undefined; if (target) edges.push({ id: `${id}->${target}`, source: id, target, relationship: "propagates_to", confidence: .8, timestamp: event.occurredAt, provenance: `event:${event.type}` }); }
  return { algorithm: "drift-world-graph-v1", nodes, edges, generatedAt: new Date().toISOString() };
}

export function traverseGraph(graph: WorldGraph, startId: string, hops = 2, direction: "downstream" | "upstream" | "both" = "both") {
  const visited = new Map<string, number>([[startId, 0]]); const queue = [startId]; const selectedEdges: GraphEdge[] = [];
  while (queue.length) { const current = queue.shift()!; const depth = visited.get(current)!; if (depth >= hops) continue; for (const edge of graph.edges) { const matches = direction === "downstream" ? edge.source === current : direction === "upstream" ? edge.target === current : edge.source === current || edge.target === current; if (!matches) continue; const next = edge.source === current ? edge.target : edge.source; selectedEdges.push(edge); if (!visited.has(next)) { visited.set(next, depth + 1); queue.push(next); } } }
  return { startId, hops, nodes: graph.nodes.filter(item => visited.has(item.id)).map(item => ({ ...item, hop: visited.get(item.id) })), edges: selectedEdges.filter((edge, index, all) => all.findIndex(other => other.id === edge.id) === index), traversalCost: selectedEdges.reduce((sum, edge) => sum + (1 / Math.max(.1, edge.confidence)), 0) };
}

export function queryWorldGraph(graph: WorldGraph, query: { kind?: GraphNodeKind; severity?: string; assetId?: number; relationship?: GraphEdge["relationship"]; startId?: string; hops?: number }) {
  const base = query.startId ? traverseGraph(graph, query.startId, query.hops ?? 2) : { nodes: graph.nodes, edges: graph.edges, traversalCost: 0 };
  const nodes = base.nodes.filter(item => (!query.kind || item.kind === query.kind) && (!query.severity || item.attributes.severity === query.severity) && (!query.assetId || item.attributes.assetId === query.assetId));
  const ids = new Set(nodes.map(item => item.id));
  return { ...base, nodes, edges: base.edges.filter(edge => (!query.relationship || edge.relationship === query.relationship) && ids.has(edge.source) && ids.has(edge.target)) };
}
