import type { SnapshotInput } from "./intelligenceEngine";
import type { DomainEvent } from "./domainEvents";

export type GraphNodeKind = "asset" | "defect" | "evidence" | "mission" | "telemetry" | "event" | "risk" | "information_gap";
export type GraphEdge = { id: string; source: string; target: string; relationship: "affects" | "observed_by" | "supports" | "targets" | "captured_by" | "propagates_to" | "precedes" | "contradicts"; confidence: number; timestamp?: string; provenance: string };
export type GraphNode = { id: string; kind: GraphNodeKind; label: string; confidence: number; observedAt?: string; state: "OBSERVED" | "CALCULATED" | "INFERRED" | "SIMULATED" | "UNKNOWN"; attributes: Record<string, unknown> };
export type WorldGraph = { algorithm: "drift-world-graph-v1"; nodes: GraphNode[]; edges: GraphEdge[]; generatedAt: string };

function node(id: string, kind: GraphNodeKind, label: string, confidence: number, state: GraphNode["state"], attributes: Record<string, unknown>, observedAt?: Date | string): GraphNode { return { id, kind, label, confidence, state, attributes, observedAt: observedAt ? new Date(observedAt).toISOString() : undefined }; }
export function buildWorldGraph(input: SnapshotInput, events: DomainEvent[] = []): WorldGraph {
  const nodes: GraphNode[] = []; const edges: GraphEdge[] = [];
  for (const asset of input.assets) nodes.push(node(`asset:${asset.id}`, "asset", asset.name, Math.min(1, (asset.criticality ?? 1) / 5), "OBSERVED", { assetType: asset.assetType, latitude: asset.latitude, longitude: asset.longitude, status: asset.status }, asset.updatedAt));
  for (const mission of input.missions) { nodes.push(node(`mission:${mission.id}`, "mission", mission.name, .95, "OBSERVED", { status: mission.status, assetId: mission.assetId }, mission.createdAt)); edges.push({ id: `mission:${mission.id}->asset:${mission.assetId}`, source: `mission:${mission.id}`, target: `asset:${mission.assetId}`, relationship: "targets", confidence: .95, timestamp: new Date(mission.createdAt).toISOString(), provenance: "missions.assetId" }); }
  for (const evidence of input.evidence) nodes.push(node(`evidence:${evidence.id}`, "evidence", evidence.fileName, evidence.qualityStatus === "pass" ? .9 : evidence.qualityStatus === "fail" ? .2 : .55, "OBSERVED", { source: evidence.source, qualityStatus: evidence.qualityStatus, latitude: evidence.latitude, longitude: evidence.longitude }, evidence.createdAt));
  for (const defect of input.defects) { const confidence = Math.max(0, Math.min(1, (defect.confidencePercent ?? 0) / 100)); nodes.push(node(`defect:${defect.id}`, "defect", defect.label, confidence, defect.reviewState === "approved" ? "OBSERVED" : "INFERRED", { severity: defect.severity, assetId: defect.assetId, missionId: defect.missionId, status: defect.status }, defect.createdAt)); edges.push({ id: `asset:${defect.assetId}->defect:${defect.id}`, source: `asset:${defect.assetId}`, target: `defect:${defect.id}`, relationship: "affects", confidence, timestamp: new Date(defect.createdAt).toISOString(), provenance: "defects.assetId" }); if (defect.evidenceId) edges.push({ id: `evidence:${defect.evidenceId}->defect:${defect.id}`, source: `evidence:${defect.evidenceId}`, target: `defect:${defect.id}`, relationship: "supports", confidence, timestamp: new Date(defect.createdAt).toISOString(), provenance: "defects.evidenceId" }); edges.push({ id: `mission:${defect.missionId}->defect:${defect.id}`, source: `mission:${defect.missionId}`, target: `defect:${defect.id}`, relationship: "observed_by", confidence: .85, timestamp: new Date(defect.createdAt).toISOString(), provenance: "defects.missionId" }); }
  for (const point of input.telemetry) { const id = `telemetry:${point.id}`; nodes.push(node(id, "telemetry", "Telemetry sample", .8, "OBSERVED", { latitude: point.latitude, longitude: point.longitude, batteryPercent: point.batteryPercent }, point.capturedAt)); edges.push({ id: `${id}->mission:${point.missionId}`, source: id, target: `mission:${point.missionId}`, relationship: "captured_by", confidence: .8, timestamp: new Date(point.capturedAt).toISOString(), provenance: "telemetry.missionId" }); }
  for (const event of events) { const id = `event:${event.eventId}`; nodes.push(node(id, "event", event.type, .8, "OBSERVED", event.payload, event.occurredAt)); const target = event.defectId ? `defect:${event.defectId}` : event.evidenceId ? `evidence:${event.evidenceId}` : event.assetId ? `asset:${event.assetId}` : event.missionId ? `mission:${event.missionId}` : undefined; if (target) edges.push({ id: `${id}->${target}`, source: id, target, relationship: "propagates_to", confidence: .8, timestamp: event.occurredAt, provenance: `event:${event.type}` }); }
  return { algorithm: "drift-world-graph-v1", nodes, edges, generatedAt: new Date().toISOString() };
}

export function traverseGraph(graph: WorldGraph, startId: string, hops = 2, direction: "downstream" | "upstream" | "both" = "both") {
  const visited = new Map<string, number>([[startId, 0]]); const queue = [startId]; const selectedEdges: GraphEdge[] = [];
  while (queue.length) { const current = queue.shift()!; const depth = visited.get(current)!; if (depth >= hops) continue; for (const edge of graph.edges) { const matches = direction === "downstream" ? edge.source === current : direction === "upstream" ? edge.target === current : edge.source === current || edge.target === current; if (!matches) continue; const next = edge.source === current ? edge.target : edge.source; selectedEdges.push(edge); if (!visited.has(next)) { visited.set(next, depth + 1); queue.push(next); } } }
  return { startId, hops, nodes: graph.nodes.filter(item => visited.has(item.id)).map(item => ({ ...item, hop: visited.get(item.id) })), edges: selectedEdges.filter((edge, index, all) => all.findIndex(other => other.id === edge.id) === index), traversalCost: selectedEdges.reduce((sum, edge) => sum + (1 / Math.max(.1, edge.confidence)), 0) };
}

export function queryWorldGraph(graph: WorldGraph, query: { kind?: GraphNodeKind; severity?: string; assetId?: number; relationship?: GraphEdge["relationship"]; startId?: string; hops?: number }) {
  const base = query.startId ? traverseGraph(graph, query.startId, query.hops ?? 2) : { nodes: graph.nodes, edges: graph.edges, traversalCost: 0 };
  const nodes = base.nodes.filter(item => (!query.kind || item.kind === query.kind) && (!query.severity || item.attributes.severity === query.severity) && (!query.assetId || item.attributes.assetId === query.assetId));
  const ids = new Set(nodes.map(item => item.id));
  return { ...base, nodes, edges: base.edges.filter(edge => (!query.relationship || edge.relationship === query.relationship) && ids.has(edge.source) && ids.has(edge.target)) };
}

export type ImpactStep = { level: number; nodeId: string; relationship: GraphEdge["relationship"]; confidence: number; reason: string };
export function analyzeGraphImpact(graph: WorldGraph, startId: string, maxHops = 3) {
  const steps: ImpactStep[] = []; const seen = new Set([startId]); let frontier = [startId];
  for (let level = 1; level <= maxHops; level += 1) { const next: string[] = []; for (const current of frontier) for (const edge of graph.edges.filter(item => item.source === current)) { if (seen.has(edge.target)) continue; seen.add(edge.target); next.push(edge.target); steps.push({ level, nodeId: edge.target, relationship: edge.relationship, confidence: edge.confidence, reason: `${edge.relationship} from ${current} with ${Math.round(edge.confidence * 100)}% relationship confidence.` }); } frontier = next; if (!frontier.length) break; }
  return { initiator: startId, directImpact: steps.filter(step => step.level === 1), secondaryImpact: steps.filter(step => step.level === 2), tertiaryImpact: steps.filter(step => step.level >= 3), impactConfidence: steps.length ? steps.reduce((sum, step) => sum + step.confidence, 0) / steps.length : 0, propagationPath: steps };
}

export function graphCentrality(graph: WorldGraph) {
  const incoming = new Map<string, number>(); const outgoing = new Map<string, number>(); for (const node of graph.nodes) { incoming.set(node.id, 0); outgoing.set(node.id, 0); }
  for (const edge of graph.edges) { incoming.set(edge.target, (incoming.get(edge.target) ?? 0) + edge.confidence); outgoing.set(edge.source, (outgoing.get(edge.source) ?? 0) + edge.confidence); }
  const metrics = graph.nodes.map(node => { const degree = (incoming.get(node.id) ?? 0) + (outgoing.get(node.id) ?? 0); const criticality = node.kind === "asset" ? Number(node.attributes.criticality ?? 1) / 5 : node.kind === "defect" && ["critical", "high"].includes(String(node.attributes.severity)) ? 1 : .4; return { nodeId: node.id, degree: (graph.edges.filter(edge => edge.source === node.id || edge.target === node.id)).length, weightedDegree: degree, dependencyDepth: incoming.get(node.id) ? 1 + Math.min(4, Math.round(incoming.get(node.id)!)) : 0, connectivity: degree / Math.max(1, graph.nodes.length - 1), criticality, leverage: Math.round((degree * .4 + criticality * .6) * 100) / 100 }; }).sort((a, b) => b.leverage - a.leverage);
  return { metrics, criticalNodes: metrics.filter(item => item.leverage >= 1).slice(0, 10), structuralVulnerabilityIndicators: metrics.filter(item => item.degree >= 2 && item.connectivity < .5).slice(0, 10) };
}

export type InformationGap = { id: string; nodeId: string; missing: string; whyItMatters: string; uncertaintyContribution: number; possibleObservation: string };
export function findInformationGaps(graph: WorldGraph): InformationGap[] {
  const gaps: InformationGap[] = []; for (const node of graph.nodes) { const adjacent = graph.edges.filter(edge => edge.source === node.id || edge.target === node.id); if (node.kind === "asset" && (!node.attributes.latitude || !node.attributes.longitude)) gaps.push({ id: `gap:location:${node.id}`, nodeId: node.id, missing: "spatial location", whyItMatters: "Spatial risk and hotspot propagation are blocked.", uncertaintyContribution: .35, possibleObservation: "geospatial asset verification" }); if (node.kind === "asset" && adjacent.filter(edge => edge.relationship === "affects").length === 0) gaps.push({ id: `gap:defects:${node.id}`, nodeId: node.id, missing: "recent defect/evidence relationship", whyItMatters: "Asset health cannot be estimated from current observations.", uncertaintyContribution: .25, possibleObservation: "targeted inspection" }); if (node.kind === "defect" && node.confidence < .6) gaps.push({ id: `gap:confidence:${node.id}`, nodeId: node.id, missing: "high-confidence classification", whyItMatters: "Risk propagation may be materially wrong.", uncertaintyContribution: .4, possibleObservation: "close-range visual review" }); }
  return gaps;
}
export function buildNextBestActions(graph: WorldGraph) { return findInformationGaps(graph).map(gap => ({ gapId: gap.id, nodeId: gap.nodeId, action: gap.possibleObservation, expectedInformationGain: Math.round(gap.uncertaintyContribution * 100), expectedRiskReduction: Math.round(gap.uncertaintyContribution * 70), cost: gap.possibleObservation.includes("targeted") ? 35 : 20, reason: gap.whyItMatters })).sort((a, b) => (b.expectedInformationGain - b.cost / 2) - (a.expectedInformationGain - a.cost / 2)); }

export function simulateCounterfactual(graph: WorldGraph, input: { nodeId: string; event: "failure" | "repair" | "inspection" }) {
  const isolated: WorldGraph = JSON.parse(JSON.stringify(graph)); const target = isolated.nodes.find(node => node.id === input.nodeId); if (!target) return { baseline: graph, counterfactual: graph, delta: { added: [], removed: [], changed: [] }, assumptions: ["Target node not present; no simulation performed."] };
  if (input.event === "failure") { target.state = "SIMULATED"; target.confidence = Math.max(.1, target.confidence - .35); target.attributes = { ...target.attributes, simulatedFailure: true }; } else if (input.event === "repair") { target.state = "SIMULATED"; target.confidence = Math.min(1, target.confidence + .25); target.attributes = { ...target.attributes, simulatedRepair: true }; } else { target.state = "SIMULATED"; target.confidence = Math.min(1, target.confidence + .15); target.attributes = { ...target.attributes, simulatedInspection: true }; }
  const changed = isolated.nodes.filter(node => { const before = graph.nodes.find(item => item.id === node.id); return JSON.stringify(before) !== JSON.stringify(node); }).map(node => ({ nodeId: node.id, before: graph.nodes.find(item => item.id === node.id), after: node })); return { baseline: graph, counterfactual: isolated, delta: { added: [], removed: [], changed }, assumptions: [`${input.event} is isolated from production state.`, "Downstream effects require a dependency edge and are not asserted without one."] };
}

export function diffWorldGraphs(before: WorldGraph, after: WorldGraph) { const beforeNodes = new Map(before.nodes.map(node => [node.id, node])); const afterNodes = new Map(after.nodes.map(node => [node.id, node])); const beforeEdges = new Map(before.edges.map(edge => [edge.id, edge])); const afterEdges = new Map(after.edges.map(edge => [edge.id, edge])); return { nodesAdded: after.nodes.filter(node => !beforeNodes.has(node.id)), nodesRemoved: before.nodes.filter(node => !afterNodes.has(node.id)), edgesAdded: after.edges.filter(edge => !beforeEdges.has(edge.id)), edgesRemoved: before.edges.filter(edge => !afterEdges.has(edge.id)), stateChanges: after.nodes.filter(node => beforeNodes.has(node.id) && JSON.stringify(beforeNodes.get(node.id)?.state) !== JSON.stringify(node.state)).map(node => ({ nodeId: node.id, before: beforeNodes.get(node.id)?.state, after: node.state })), riskChanges: after.nodes.filter(node => beforeNodes.has(node.id) && beforeNodes.get(node.id)!.confidence !== node.confidence).map(node => ({ nodeId: node.id, before: beforeNodes.get(node.id)!.confidence, after: node.confidence })) }; }
