import { useEffect, useMemo, useRef, useState } from "react";
import { Eye, Layers3, LocateFixed, Search } from "lucide-react";
import { trpc } from "@/lib/trpc";

type LayerKey = "defects" | "assets" | "cameras" | "candidates";
const colors: Record<LayerKey, string> = { defects: "#ef4444", assets: "#2563eb", cameras: "#9333ea", candidates: "#f59e0b" };
function loadLeaflet() { if (!document.getElementById("leaflet-css")) { const css = document.createElement("link"); css.id = "leaflet-css"; css.rel = "stylesheet"; css.href = "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"; document.head.appendChild(css); } return new Promise<any>(resolve => { if ((window as any).L) return resolve((window as any).L); const script = document.createElement("script"); script.src = "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"; script.onload = () => resolve((window as any).L); document.body.appendChild(script); }); }
function point(row: any) { const lat = Number(row.latitude), lng = Number(row.longitude); return Number.isFinite(lat) && Number.isFinite(lng) ? [lat, lng] as [number, number] : null; }
function escape(value: unknown) { return String(value ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string)); }
export default function GodsEyeMap() {
  const mapEl = useRef<HTMLDivElement>(null); const mapRef = useRef<any>(null); const layersRef = useRef<Record<LayerKey, any[]>>({ defects: [], assets: [], cameras: [], candidates: [] });
  const data = trpc.drift.godEye.useQuery(); const [query, setQuery] = useState(""); const [satellite, setSatellite] = useState(true); const [active, setActive] = useState<Record<LayerKey, boolean>>({ defects: true, assets: true, cameras: true, candidates: true });
  const rows = data.data;
  const matches = useMemo(() => { const q = query.toLowerCase().trim(); if (!q || !rows) return []; return [...rows.defects, ...rows.assets, ...rows.cameras, ...rows.candidates].filter(row => JSON.stringify(row).toLowerCase().includes(q)).slice(0, 8); }, [query, rows]);
  useEffect(() => { let disposed = false; loadLeaflet().then(L => { if (disposed || !mapEl.current || mapRef.current) return; const map = L.map(mapEl.current, { center: [28.6139, 77.209], zoom: 12, zoomControl: true }); const imagery = L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}", { attribution: "Tiles © Esri" }).addTo(map); (map as any).__imagery = imagery; (map as any).__street = L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { attribution: "© OpenStreetMap contributors" }); mapRef.current = map; }); return () => { disposed = true; mapRef.current?.remove(); mapRef.current = null; }; }, []);
  useEffect(() => { const map = mapRef.current; if (!map || !rows || !(window as any).L) return; const L = (window as any).L; (Object.keys(layersRef.current) as LayerKey[]).forEach(key => { layersRef.current[key].forEach(layer => layer.remove()); layersRef.current[key] = []; }); const bounds: any[] = [];
    const add = (key: LayerKey, records: any[], title: (r: any) => string, detail: (r: any) => string) => records.forEach(row => { const p = point(row); if (!p) return; const marker = L.circleMarker(p, { radius: key === "cameras" ? 7 : 8, color: "#fff", weight: 2, fillColor: colors[key], fillOpacity: .92 }); marker.bindPopup(`<strong>${escape(title(row))}</strong><br/>${escape(detail(row))}<br/><small>GPS ${p[0].toFixed(6)}, ${p[1].toFixed(6)}</small>`); if (active[key]) marker.addTo(map); layersRef.current[key].push(marker); bounds.push(p); });
    add("defects", rows.defects, r => `MALFUNCTION · ${r.label}`, r => `Severity: ${r.severity} · Status: ${r.status}`); add("assets", rows.assets, r => `ASSET · ${r.name}`, r => `${r.assetType} · ${r.status} · criticality ${r.criticality}/5`); add("cameras", rows.cameras, r => `AUTHORIZED CCTV · ${r.displayName}`, r => `${r.cameraCode} · ${r.zoneLabel} · ${r.accessClassification}`); add("candidates", rows.candidates, r => `CCTV CANDIDATE · ${r.candidateType}`, r => `${r.zoneLabel} · ${r.status} · confidence ${r.detectionConfidence}%`); if (bounds.length && !query) map.fitBounds(bounds, { padding: [35, 35], maxZoom: 16 }); }, [rows, active, query]);
  useEffect(() => { const map = mapRef.current; if (!map) return; const imagery = (map as any).__imagery, street = (map as any).__street; if (satellite) { if (!map.hasLayer(imagery)) imagery.addTo(map); if (map.hasLayer(street)) map.removeLayer(street); } else { if (!map.hasLayer(street)) street.addTo(map); if (map.hasLayer(imagery)) map.removeLayer(imagery); } }, [satellite]);
  return <section className="workspace-page"><div className="workspace-header"><div><span className="eyebrow">GOD'S EYE · LIVE GEOSPATIAL OPERATIONS</span><h2>Bird’s-eye malfunction map</h2><p className="workspace-lede">Satellite-style view linked to DRIFT records. Search a defect, asset, authorized camera, or reviewed CCTV candidate to pinpoint its exact stored coordinates.</p></div><div className="rounded-xl border border-violet-800 bg-slate-950 px-5 py-4 text-white"><Eye className="mb-2 text-violet-300" /><span className="eyebrow text-violet-300">DATABASE LAYER</span><div className="text-lg font-bold">{rows?.available ? "LIVE · LINKED" : "OFFLINE"}</div></div></div><div className="grid grid-cols-1 gap-4 md:grid-cols-4">{([['defects','Malfunctions'],['assets','Assets'],['cameras','Authorized CCTV'],['candidates','CCTV candidates']] as const).map(([key, label]) => <button key={key} type="button" onClick={() => setActive(s => ({ ...s, [key]: !s[key] }))} className={`rounded-xl border p-4 text-left ${active[key] ? "bg-white" : "bg-slate-100 opacity-60"}`}><span className="eyebrow" style={{ color: colors[key] }}>{label}</span><strong className="mt-1 block text-2xl">{rows?.[key]?.length ?? 0}</strong><span className="text-xs text-slate-500">{active[key] ? "visible on map" : "hidden"}</span></button>)}</div><div className="mt-5 overflow-hidden rounded-2xl border bg-slate-900"><div className="flex flex-wrap items-center gap-3 border-b border-slate-700 bg-slate-950 p-3"><div className="relative min-w-[280px] flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input className="w-full rounded-lg border-0 bg-slate-800 pl-9 text-white" placeholder="Search malfunction, asset, CCTV code, zone..." value={query} onChange={e => setQuery(e.target.value)} /></div><button type="button" className="rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold text-white" onClick={() => setSatellite(s => !s)}><Layers3 className="mr-2 inline h-4 w-4" />{satellite ? "SATELLITE" : "STREET"}</button><button type="button" className="rounded-lg bg-slate-700 px-4 py-2 text-sm text-white" onClick={() => mapRef.current?.setView([28.6139, 77.209], 12)}><LocateFixed className="mr-2 inline h-4 w-4" />RESET VIEW</button></div>{matches.length > 0 && <div className="border-b border-slate-700 bg-slate-900 p-2">{matches.map((row: any, i) => <button key={i} type="button" className="mr-2 rounded bg-slate-800 px-3 py-1 text-xs text-white" onClick={() => { const p = point(row); if (p) mapRef.current?.flyTo(p, 18); }}>{row.name ?? row.label ?? row.displayName ?? row.candidateType}</button>)}</div>}<div ref={mapEl} className="h-[620px] w-full" /></div><p className="mt-3 text-xs text-slate-500">Privacy boundary: only authorized, non-expired camera source records and reviewed database candidates appear. This map does not discover, scrape, or expose arbitrary public/private cameras.</p></section>;
}
