import { useEffect, useMemo, useRef, useState } from "react";
import { cn } from "@/lib/utils";

type Severity = "low" | "medium" | "high" | "critical";
type InspectionMapProps = { defects: Array<{ id: number; label: string; severity: Severity; latitude: string | number; longitude: string | number }>; telemetry: Array<{ latitude: string | number; longitude: string | number }>; selectedId?: number; onSelect: (id: number) => void; className?: string };
type PublicBridgeContext = { structureNumber: string; title: string; latitude: number; longitude: number; deckCondition: string; source: string; sourceUrl: string };

const colors: Record<Severity, string> = { critical: "#c81e1e", high: "#e26d16", medium: "#b98600", low: "#177a47" };
const publicNbiBridgeContext: PublicBridgeContext[] = [
  { structureNumber: "0518", title: "Johnson River", latitude: 63.704797, longitude: -144.640464, deckCondition: "4", source: "USDOT/BTS NBI 2025", sourceUrl: "https://geodata.bts.gov/datasets/usdot::national-bridge-inventory/about" },
  { structureNumber: "0574", title: "Gulkana River", latitude: 62.268856, longitude: -145.373803, deckCondition: "4", source: "USDOT/BTS NBI 2025", sourceUrl: "https://geodata.bts.gov/datasets/usdot::national-bridge-inventory/about" },
  { structureNumber: "0581", title: "Upper Miller Creek", latitude: 63.375533, longitude: -145.729814, deckCondition: "4", source: "USDOT/BTS NBI 2025", sourceUrl: "https://geodata.bts.gov/datasets/usdot::national-bridge-inventory/about" },
];

let googleMapsPromise: Promise<typeof google> | null = null;
function loadGoogleMaps(apiKey: string) {
  if (window.google?.maps) return Promise.resolve(window.google);
  if (googleMapsPromise) return googleMapsPromise;
  googleMapsPromise = new Promise((resolve, reject) => {
    const existing = document.getElementById("drift-google-maps-sdk") as HTMLScriptElement | null;
    if (existing) { existing.addEventListener("load", () => resolve(window.google), { once: true }); existing.addEventListener("error", () => reject(new Error("Google Maps could not be loaded.")), { once: true }); return; }
    const script = document.createElement("script"); script.id = "drift-google-maps-sdk"; script.src = `https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(apiKey)}&v=weekly`; script.async = true;
    script.onload = () => resolve(window.google); script.onerror = () => reject(new Error("Google Maps could not be loaded.")); document.head.appendChild(script);
  });
  return googleMapsPromise;
}
function asCoordinates(value: { latitude: string | number; longitude: string | number }) { const lat = Number(value.latitude); const lng = Number(value.longitude); return Number.isFinite(lat) && Number.isFinite(lng) && lat >= -90 && lat <= 90 && lng >= -180 && lng <= 180 ? { lat, lng } : null; }

export function InspectionMap({ defects, telemetry, selectedId, onSelect, className }: InspectionMapProps) {
  const mapElement = useRef<HTMLDivElement>(null); const mapRef = useRef<google.maps.Map | null>(null); const projectMarkers = useRef<google.maps.Marker[]>([]); const contextMarkers = useRef<google.maps.Marker[]>([]); const [mapState, setMapState] = useState<"loading" | "ready" | "missing-key" | "error">("loading");
  const apiKey = import.meta.env.VITE_GOOGLE_MAPS_API_KEY?.trim();
  const validDefects = useMemo(() => defects.map(defect => ({ defect, point: asCoordinates(defect) })).filter((item): item is { defect: InspectionMapProps["defects"][number]; point: { lat: number; lng: number } } => Boolean(item.point)), [defects]);
  const validTelemetry = useMemo(() => telemetry.map(asCoordinates).filter((point): point is { lat: number; lng: number } => Boolean(point)), [telemetry]);
  const severityCounts = useMemo(() => (Object.keys(colors) as Severity[]).map(severity => ({ severity, count: validDefects.filter(item => item.defect.severity === severity).length })), [validDefects]);
  useEffect(() => { if (!apiKey) { setMapState("missing-key"); return; } let cancelled = false; setMapState("loading"); loadGoogleMaps(apiKey).then(() => { if (cancelled || !mapElement.current) return; const center = validDefects[0]?.point ?? { lat: publicNbiBridgeContext[0]!.latitude, lng: publicNbiBridgeContext[0]!.longitude }; mapRef.current = new window.google.maps.Map(mapElement.current, { center, zoom: validDefects.length ? 15 : 6, mapTypeControl: true, streetViewControl: false, fullscreenControl: true, clickableIcons: false, gestureHandling: "cooperative" }); setMapState("ready"); }).catch(() => { if (!cancelled) setMapState("error"); }); return () => { cancelled = true; }; }, [apiKey]);
  useEffect(() => { const map = mapRef.current; if (!map || mapState !== "ready" || !window.google?.maps) return; projectMarkers.current.forEach(marker => marker.setMap(null)); contextMarkers.current.forEach(marker => marker.setMap(null)); projectMarkers.current = []; contextMarkers.current = []; const bounds = new window.google.maps.LatLngBounds(); const infoWindow = new window.google.maps.InfoWindow(); validDefects.forEach(({ defect, point }) => { const marker = new window.google.maps.Marker({ map, position: point, title: `DRIFT project finding: ${defect.label}`, label: { text: defect.severity[0]!.toUpperCase(), color: "#ffffff", fontWeight: "700" }, icon: { path: window.google.maps.SymbolPath.CIRCLE, fillColor: colors[defect.severity], fillOpacity: 1, strokeColor: "#ffffff", strokeWeight: selectedId === defect.id ? 3 : 1.5, scale: selectedId === defect.id ? 12 : 10 } }); marker.addListener("click", () => { onSelect(defect.id); infoWindow.setContent(`<div style="max-width:230px;font:13px Arial,sans-serif"><strong>DRIFT project finding</strong><br/>${defect.label}<br/>Severity: ${defect.severity}<br/>Coordinates: ${point.lat.toFixed(6)}, ${point.lng.toFixed(6)}<br/><em>Engineer review required.</em></div>`); infoWindow.open({ map, anchor: marker }); }); projectMarkers.current.push(marker); bounds.extend(point); }); validTelemetry.forEach(point => { const marker = new window.google.maps.Marker({ map, position: point, clickable: false, icon: { path: window.google.maps.SymbolPath.CIRCLE, fillColor: "#16b7d4", fillOpacity: .8, strokeColor: "#ffffff", strokeWeight: 1, scale: 3 } }); projectMarkers.current.push(marker); bounds.extend(point); }); publicNbiBridgeContext.forEach(context => { const marker = new window.google.maps.Marker({ map, position: { lat: context.latitude, lng: context.longitude }, title: `Public NBI context: ${context.title}`, label: { text: "NBI", color: "#ffffff", fontSize: "9px", fontWeight: "700" }, icon: { path: window.google.maps.SymbolPath.BACKWARD_CLOSED_ARROW, fillColor: "#5646b0", fillOpacity: .95, strokeColor: "#ffffff", strokeWeight: 1.5, scale: 6 } }); marker.addListener("click", () => { infoWindow.setContent(`<div style="max-width:250px;font:13px Arial,sans-serif"><strong>Public NBI context only</strong><br/>${context.title} · Structure ${context.structureNumber}<br/>Published deck-condition field: ${context.deckCondition}<br/><em>2025 public inventory record. Not a DRIFT site, live defect, ticket, or safety determination.</em></div>`); infoWindow.open({ map, anchor: marker }); }); contextMarkers.current.push(marker); }); if (validDefects.length || validTelemetry.length) map.fitBounds(bounds, 80); }, [mapState, onSelect, selectedId, validDefects, validTelemetry]);
  const showNbiContext = () => { const map = mapRef.current; if (!map || !window.google?.maps) return; const bounds = new window.google.maps.LatLngBounds(); publicNbiBridgeContext.forEach(point => bounds.extend({ lat: point.latitude, lng: point.longitude })); map.fitBounds(bounds, 60); };
  return <section className={cn("relative min-h-[430px] overflow-hidden border border-slate-700 bg-slate-950", className)} aria-label="Google Maps infrastructure context"><div ref={mapElement} className="absolute inset-0" />{mapState === "loading" && <div className="absolute inset-0 grid place-items-center bg-slate-950 text-center text-xs font-semibold uppercase tracking-[.14em] text-slate-200">Loading Google Maps context…</div>}{mapState === "missing-key" && <div className="absolute inset-0 grid place-items-center bg-slate-950 p-8 text-center text-xs font-semibold uppercase tracking-[.14em] text-slate-200"><div><strong className="block text-sm text-white">Google Maps configuration required</strong><span className="mt-3 block max-w-md normal-case font-normal leading-5 tracking-normal text-slate-400">Set the browser-visible Vercel variable <code>VITE_GOOGLE_MAPS_API_KEY</code> with a domain-restricted Google Maps JavaScript API key. No fallback map or invented locations are shown.</span></div></div>}{mapState === "error" && <div className="absolute inset-0 grid place-items-center bg-slate-950 p-8 text-center text-xs font-semibold uppercase tracking-[.14em] text-slate-200"><div><strong className="block text-sm text-white">Google Maps could not load</strong><span className="mt-3 block max-w-md normal-case font-normal leading-5 tracking-normal text-slate-400">Verify the browser key, allowed Vercel domain, and Google Maps JavaScript API. Project and public-context markers remain intentionally unavailable until the map is live.</span></div></div>}<div className="pointer-events-none absolute left-3 top-3 z-10 max-w-[calc(100%-1.5rem)] bg-slate-950/95 px-3 py-2 text-[10px] font-semibold uppercase tracking-[.13em] text-slate-100 shadow-xl"><div>{validDefects.length} DRIFT project finding{validDefects.length === 1 ? "" : "s"} · {validTelemetry.length} telemetry point{validTelemetry.length === 1 ? "" : "s"}</div><div className="mt-2 flex flex-wrap gap-2 text-[9px] tracking-[.08em]">{severityCounts.map(item => <span key={item.severity} className="flex items-center gap-1"><i className="h-2 w-2 rounded-full" style={{ backgroundColor: colors[item.severity] }} />{item.count} {item.severity}</span>)}</div></div><div className="absolute bottom-3 left-3 right-3 z-10 flex flex-wrap items-center gap-2 bg-slate-950/95 p-2.5 text-[9px] font-semibold uppercase tracking-[.1em] text-slate-100 shadow-xl"><span className="mr-auto">● DRIFT evidence &nbsp; ◆ public NBI context (not a live defect)</span><button type="button" onClick={showNbiContext} className="pointer-events-auto border border-violet-300/70 bg-violet-900/90 px-2.5 py-1.5 text-[9px] font-bold text-white">FOCUS PUBLIC NBI CONTEXT</button><a className="pointer-events-auto border border-slate-500 px-2.5 py-1.5 text-[9px] font-bold text-slate-100" href="https://geodata.bts.gov/datasets/usdot::national-bridge-inventory/about" target="_blank" rel="noreferrer">NBI SOURCE</a></div></section>;
}
