import { useEffect, useRef, useState } from "react";
import { Box, LoaderCircle, MousePointer2 } from "lucide-react";
let threePromise: Promise<any> | null = null;
function loadThree() { if ((window as any).THREE) return Promise.resolve((window as any).THREE); if (threePromise) return threePromise; threePromise = new Promise(resolve => { const script = document.createElement("script"); script.src = "https://unpkg.com/three@0.170.0/build/three.min.js"; script.onload = () => { const loader = document.createElement("script"); loader.src = "https://unpkg.com/three@0.170.0/examples/js/loaders/GLTFLoader.js"; loader.onload = () => resolve((window as any).THREE); document.head.appendChild(loader); }; document.head.appendChild(script); }); return threePromise; }
export default function ReconstructionViewer({ artifactUrl }: { artifactUrl?: string | null }) {
  const host = useRef<HTMLDivElement>(null); const [state, setState] = useState("idle"); const backendOrigin = (import.meta.env.VITE_BACKEND_URL || "https://drift-node-api.onrender.com").replace(/\/$/, ""); const resolvedArtifactUrl = artifactUrl ? (artifactUrl.startsWith("http") ? artifactUrl : `${backendOrigin}${artifactUrl}`) : null;
  useEffect(() => { if (!resolvedArtifactUrl || !host.current) return; let disposed = false; let renderer: any; let animation = 0; loadThree().then(THREE => { if (disposed || !host.current) return; const scene = new THREE.Scene(); scene.background = new THREE.Color(0x07111f); scene.add(new THREE.HemisphereLight(0x9ddcff, 0x15101f, 2)); const camera = new THREE.PerspectiveCamera(45, host.current.clientWidth / 440, .1, 10000); camera.position.set(5, 4, 8); renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(host.current.clientWidth, 440); host.current.replaceChildren(renderer.domElement); scene.add(new THREE.GridHelper(20, 20, 0x164e63, 0x0f293d)); setState("loading"); const loader = new THREE.GLTFLoader(); loader.load(resolvedArtifactUrl, (gltf: any) => { scene.add(gltf.scene); setState("ready"); }, undefined, () => setState("failed")); let down = false, x = 0; const onDown = (e: PointerEvent) => { down = true; x = e.clientX; }; const onUp = () => { down = false; }; const onMove = (e: PointerEvent) => { if (!down) return; scene.rotation.y += (e.clientX - x) * .005; x = e.clientX; }; renderer.domElement.addEventListener("pointerdown", onDown); renderer.domElement.addEventListener("pointerup", onUp); renderer.domElement.addEventListener("pointermove", onMove); const tick = () => { animation = requestAnimationFrame(tick); renderer.render(scene, camera); }; tick(); return () => { cancelAnimationFrame(animation); renderer.domElement.removeEventListener("pointerdown", onDown); renderer.domElement.removeEventListener("pointerup", onUp); renderer.domElement.removeEventListener("pointermove", onMove); renderer.dispose(); }; }).catch(() => setState("failed")); return () => { disposed = true; cancelAnimationFrame(animation); renderer?.dispose?.(); }; }, [resolvedArtifactUrl]);
  return <article className="panel overflow-hidden"><div className="flex items-center justify-between border-b p-4"><div><span className="eyebrow">WEBGL MESH INSPECTOR</span><h3>Textured 3D reconstruction</h3></div>{state === "loading" ? <LoaderCircle className="animate-spin text-cyan-600" /> : <Box className="text-cyan-600" />}</div>{resolvedArtifactUrl ? <><div ref={host} className="h-[440px] w-full" />{state === "ready" && <p className="border-t bg-slate-50 p-3 text-xs text-slate-600"><MousePointer2 className="mr-1 inline h-3 w-3" />Drag to rotate. Published GLB artifact loaded from the reconstruction worker.</p>}{state === "failed" && <p className="p-4 text-sm text-amber-800">GLB artifact could not be loaded. Check that the worker artifact volume is mounted into the API and CORS allows the public frontend.</p>}</> : <div className="flex h-[440px] items-center justify-center bg-slate-950 p-8 text-center text-sm text-slate-300">Select a completed reconstruction job with a published GLB artifact to open the real WebGL viewer.<br /><span className="mt-2 block text-xs text-slate-500">No geometry is generated in the browser.</span></div>}</article>;
}
