import { useMemo, useRef, useState } from "react";
import { Boxes, CheckCircle2, FileVideo, MapPinned, Play, UploadCloud } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import ReconstructionViewer from "@/components/ReconstructionViewer";

export default function ReconstructionWorkspace() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<File | null>(null);
  const [name, setName] = useState("North campus single-pass reconstruction");
  const [lat, setLat] = useState("28.6139");
  const [lng, setLng] = useState("77.2090");
  const [altitude, setAltitude] = useState("80");
  const [duration, setDuration] = useState("600");
  const [sourceUrl, setSourceUrl] = useState("");
  const [resolution, setResolution] = useState<"1080p" | "4k">("4k");
  const [sensors, setSensors] = useState({ hasImu: true, hasRtk: false, hasBarometer: true, hasIntrinsics: false });
  const [lastJob, setLastJob] = useState<any>(null);
  const [selectedJob, setSelectedJob] = useState<any>(null);
  const jobs = trpc.drift.reconstruction.list.useQuery(undefined, { refetchInterval: 10000, retry: false });
  const uploadSource = trpc.drift.reconstruction.uploadSource.useMutation();
  const create = trpc.drift.reconstruction.create.useMutation({ onSuccess: data => { setLastJob(data); jobs.refetch(); toast.success("Original video uploaded and reconstruction job queued"); }, onError: error => toast.error(error.message) });
  const input = useMemo(() => ({ fileName: file?.name ?? "single-pass-drone-video.mp4", mimeType: file?.type || "video/mp4", sizeBytes: file?.size || 1000000, sourceUrl: sourceUrl.trim(), latitude: Number(lat), longitude: Number(lng), altitudeMeters: Number(altitude), durationSeconds: Number(duration), resolution, ...sensors }), [file, sourceUrl, lat, lng, altitude, duration, resolution, sensors]);
  const quality = useMemo(() => { const completeness = Object.values(sensors).filter(Boolean).length / 4; const score = Math.round((completeness * 0.4 + (resolution === "4k" ? 1 : .72) * .35 + (Number(duration) >= 30 ? 1 : .65) * .25) * 100); return { score, grade: score >= 85 ? "A" : score >= 70 ? "B" : score >= 55 ? "C" : "D" }; }, [sensors, resolution, duration]);
  const isRealSourceUrl = (() => { try { const url = new URL(sourceUrl.trim()); return url.protocol === "https:" && !["example.com", "www.example.com", "storage.example.com"].includes(url.hostname); } catch { return false; } })();
  const submit = async () => { if (!file) { toast.error("Choose the original drone video first."); return; } if (sourceUrl && !isRealSourceUrl) { toast.error("The worker URL is invalid. Remove the example URL; the selected video will be uploaded automatically."); return; } try { const buffer = await file.arrayBuffer(); const bytes = new Uint8Array(buffer); let binary = ""; const chunk = 0x8000; for (let i = 0; i < bytes.length; i += chunk) binary += String.fromCharCode(...Array.from(bytes.subarray(i, Math.min(i + chunk, bytes.length)))); const uploaded = await uploadSource.mutateAsync({ fileName: file.name, mimeType: file.type || "video/mp4", base64: btoa(binary) }); create.mutate({ name, ...input, fileName: uploaded.fileName, mimeType: uploaded.mimeType, sizeBytes: uploaded.sizeBytes, sourceUrl: uploaded.sourceUrl }); } catch (error) { toast.error(error instanceof Error ? error.message : "Video upload failed"); } };
  return <section className="workspace-page">
    <div className="workspace-header"><div><span className="eyebrow">SINGLE-PASS PHOTOGRAMMETRY</span><h2>3D Reconstruction Lab</h2><p className="workspace-lede">Turn one geotagged drone video into a measurable, georeferenced scene. Every run keeps the original capture, sensor provenance, quality score, and export contract separate from generated geometry.</p></div><div className="rounded-xl border border-slate-800 bg-slate-950 px-5 py-4 text-white"><span className="eyebrow text-cyan-300">QUALITY GATE</span><div className="mt-1 text-3xl font-bold">{quality.score}<span className="text-base text-slate-400"> / 100 · {quality.grade}</span></div></div></div>
    <div className="grid grid-cols-1 gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <article className="panel p-5"><div className="panel-heading"><div><span className="eyebrow">01 · PUBLIC CAPTURE INTAKE</span><h3>Launch a reconstruction run</h3></div><FileVideo className="text-cyan-600" /></div><p className="mt-3 rounded-lg bg-cyan-50 p-3 text-sm text-cyan-950">The selected original video is now uploaded to configured object storage before the job is created. No job is created until the upload succeeds.</p><div className="mt-4 space-y-4"><label>Mission name<input value={name} onChange={e => setName(e.target.value)} /></label><button type="button" className="flex w-full items-center justify-center gap-3 rounded-xl border-2 border-dashed border-cyan-300 bg-cyan-50 p-7 text-cyan-900" onClick={() => inputRef.current?.click()}><UploadCloud />{file ? <span>{file.name} · {(file.size / 1024 / 1024).toFixed(1)} MB · ready to upload</span> : <span>Choose MP4 / MOV / WebM video</span>}</button><input ref={inputRef} hidden type="file" accept="video/mp4,video/quicktime,video/webm,video/x-msvideo" onChange={e => setFile(e.target.files?.[0] ?? null)} /><p className="text-xs text-slate-500">Optional: paste an existing real HTTPS source URL. Otherwise the selected file uploads automatically.</p><div className="grid grid-cols-2 gap-3"><label>Latitude<input value={lat} onChange={e => setLat(e.target.value)} /></label><label>Longitude<input value={lng} onChange={e => setLng(e.target.value)} /></label><label>Altitude (m)<input value={altitude} onChange={e => setAltitude(e.target.value)} /></label><label>Duration (sec)<input value={duration} onChange={e => setDuration(e.target.value)} /></label></div><label>Capture resolution<select value={resolution} onChange={e => setResolution(e.target.value as any)}><option value="4k">4K · recommended</option><option value="1080p">1080p</option></select></label><div className="grid grid-cols-2 gap-2 text-sm">{([['hasImu','IMU trajectory'],['hasRtk','RTK / PPK corrections'],['hasBarometer','Barometric altitude'],['hasIntrinsics','Camera intrinsics']] as const).map(([key, label]) => <label key={key} className="flex flex-row items-center gap-2 rounded-lg border bg-slate-50 p-3"><input type="checkbox" checked={sensors[key]} onChange={e => setSensors(s => ({ ...s, [key]: e.target.checked }))} />{label}</label>)}</div><button type="button" className="primary-action w-full" disabled={create.isPending || uploadSource.isPending || !file} onClick={submit}><Play />{uploadSource.isPending ? "UPLOADING ORIGINAL VIDEO" : create.isPending ? "QUEUING PIPELINE" : "UPLOAD AND START RECONSTRUCTION"}</button></div></article>
      <article className="panel p-5"><div className="panel-heading"><div><span className="eyebrow">02 · RECONSTRUCTION GRAPH</span><h3>Production pipeline contract</h3></div><Boxes className="text-violet-600" /></div><div className="mt-4 space-y-2">{(lastJob?.stages ?? ['ingest','metadata_validation','frame_sampling','visual_odometry','sparse_cloud','dense_cloud','mesh_texturing','semantic_layers','georeference','quality_gate','publish_artifacts']).map((stage: any, i: number) => <div key={stage.stage ?? stage} className="flex items-center gap-3 rounded-lg border bg-white p-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-slate-900 text-xs text-white">{i + 1}</span><span className="font-medium">{stage.stage ?? stage}</span><span className="ml-auto text-xs uppercase text-slate-400">{stage.status ?? 'pending'}</span></div>)}</div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-lg bg-emerald-50 p-3"><b>Output types</b><p>GLB · LAS · GeoTIFF · OBJ · FBX</p></div><div className="rounded-lg bg-amber-50 p-3"><b>Accuracy guard</b><p>{sensors.hasRtk ? "RTK-assisted georeference" : "GCP review recommended"}</p></div></div></article>
    </div>
    <article className="panel mt-5 p-5"><div className="panel-heading"><div><span className="eyebrow">03 · JOB LEDGER</span><h3>Traceable reconstruction runs</h3></div><MapPinned className="text-slate-500" /></div>{lastJob && <div className="mb-4 rounded-lg border border-cyan-200 bg-cyan-50 p-4"><CheckCircle2 className="mr-2 inline text-cyan-700" />Queued <b>{lastJob.name}</b> · job {lastJob.jobKey} · no geometry is published until the quality gate passes.</div>}<div className="space-y-2">{jobs.data?.length ? jobs.data.map((job: any) => <button type="button" key={job.jobKey} onClick={() => setSelectedJob(job)} className={`grid w-full grid-cols-[1fr_auto_auto] items-center gap-3 rounded-lg border p-3 text-left ${selectedJob?.jobKey === job.jobKey ? "border-cyan-500 bg-cyan-50" : "bg-white"}`}><div><b>{job.name}</b><p className="text-xs text-slate-500">{job.inputFileName} · {job.latitude}, {job.longitude}</p></div><span className="text-sm font-semibold">{job.qualityReport?.score ?? "—"}/100</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs uppercase">{job.status}</span></button>) : <p className="text-sm text-slate-500">No reconstruction runs yet. Submit an original flight capture to create the first traceable job.</p>}</div></article>
    <div className="mt-5"><ReconstructionViewer artifactUrl={selectedJob?.artifactManifest?.artifacts?.find((artifact: any) => artifact.format === "glb")?.url ?? null} /></div>
  </section>;
}
